---
#- name: downloadtest 
#  win_shell: echo 'test test test'
- name: Display the config
  debug:
    msg: "dans role"
- name: Install Apache
  apt: name=apache2 update_cache=yes state=latest
- name: run powershell script
  script: library\helloworld.ps1
