---
#- name: downloadtest 
#  win_shell: echo 'test test test'
- name: Display the config
  debug:
    msg: "dans role"
#- name: install erlang
#  win_package:
#    path: C:\ansible_windows\otp_win64_23.0.exe
#    creates_path: C:\ansible_windows\otp_win64_23.0.exe
#    creates_version: 23.0
#    state: present
- name: install rabbitmq
  win_package:
    path: C:\ansible_windows\rabbitmq-server-3.8.5.exe
    #creates_path: C:\ansible_windows\rabbitmq-server-3.8.5.exe
    #creates_version: 3.8.5
    product_id: rabbitmq-server-3.8.5
    state: present
- name: Install Apache
  apt: name=apache2 update_cache=yes state=latest
- name: run powershell script
  script: library\helloworld.ps1
